/**
 * Orthogonal intents (updated 2026-08-09 Asia/Shanghai):
 * 1. Expose the public Core package contract through one stable barrel.
 * 2. Keep filesystem, CLI, Root Context, workflow/operation inputs, live, and static types source-distinct.
 * 3. Publish browser-safe subpath contracts, including Dashboard Summary v2 and the external Codex command
 *    observation root, without forcing browser runtimes through this root.
 * 4. Export the typed Git repository binding and Dashboard provenance contracts.
 * 5. Export the generic CLI-backed projection lifecycle and argv-safe subprocess/invocation/tree owners while preserving browser-safe subpaths.
 *
 * Re-export the v9 admission, capability, and registry-selection boundaries.
 * Original request (2026-07-15): "用强类型合同承载 OpenSpec 1.6 的客观事实。"
 * Original request (2026-07-17): "Root-scoped stream startup returns an owned handle, not a void cancel function."
 * Original request (2026-07-18): "Profile/Drift must refresh with external environment config changes."
 * Derived requirement (2026-07-19): "Static Git remains unavailable and must not fabricate live binding provenance."
 * Derived requirement (2026-07-19): "Project Binding writes return typed launch and transition evidence."
 * Derived requirement (2026-07-20): "Environment-global Codex command observation shares Core path truth."
 * Original request (2026-07-26): "界面上仍然可以读到缓存，但它也能知道这个缓存现在正在被更新中。"
 * Original request (2026-08-01): preserve typed OpenSpec 1.7 Archive Instructions publicly.
 * Original request (2026-08-05): Continue the Windows adaptation and fix equivalent failures together.
 * Original request (2026-08-04): "Make pnpm openspecui start and equivalent package scripts work on Windows."
 
 * Original request (2026-08-15): "v9的适配需要同时适配 1.8和1.9。"*/
/**
 * @openspecui/core
 *
 * Core library for OpenSpec file operations, parsing, and validation.
 * Provides filesystem adapter, markdown parser, and reactive file system for
 * spec-driven development workflows.
 *
 * @packageDocumentation
 */

// Filesystem adapter for reading/writing OpenSpec files
export { OpenSpecAdapter, type ArchiveMeta, type ChangeMeta, type SpecMeta } from './adapter.js'
export type {
  ChangeProjectionBatch,
  ChangeProjectionData,
  ChangeProjectionRowError,
} from './change-projection.js'

// Markdown parser for spec and change documents
export { MarkdownParser } from './parser.js'

export {
  parseMarkdownFacts,
  toMarkdownFactKind,
  type MarkdownFact,
  type MarkdownFactKind,
  type MarkdownFactsDocument,
  type MarkdownSourcePoint,
  type MarkdownSourceRange,
} from './markdown-facts.js'

export {
  MarkdownReadingPluginRegistry,
  buildMarkdownParentMap,
  createMarkdownReadingDocument,
  createMarkdownReadingDocumentFromFacts,
  getMarkdownAnnotation,
  getMarkdownAnnotationsForFact,
  getMarkdownFactSpan,
  getMarkdownHeadingEnd,
  getMarkdownHeadingFacts,
  sortMarkdownReadingPlugins,
  trimMarkdownSlice,
  type MarkdownAnnotation,
  type MarkdownAnnotationConfidence,
  type MarkdownAnnotationContext,
  type MarkdownAnnotationInput,
  type MarkdownAnnotationRule,
  type MarkdownFactSpan,
  type MarkdownProjectionContext,
  type MarkdownProjectionRule,
  type MarkdownReadingDocument,
  type MarkdownReadingLookup,
  type MarkdownReadingPlugin,
} from './markdown-reading.js'

export {
  annotateOpenSpecFacts,
  annotateOpenSpecMarkdown,
  builtinOpenSpecReadingPlugin,
  getOpenSpecAnnotation,
  getOpenSpecAnnotationsForFact,
  openSpecAnnotationRules,
  type AnnotatedOpenSpecDocument,
  type OpenSpecAnnotation,
  type OpenSpecAnnotationConfidence,
  type OpenSpecScenarioStepKeyword,
  type OpenSpecSemanticKind,
} from './openspec-annotations.js'

export {
  OPEN_SPEC_READING_SECTIONS_PROJECTION_ID,
  OPEN_SPEC_SPEC_PROJECTION_ID,
  createOpenSpecReadingPlugin,
  getOpenSpecProjectionAnnotation,
  getOpenSpecReadingSections,
  parseOpenSpecMarkdownToSpec,
  projectAnnotatedOpenSpecToSpec,
  projectOpenSpecMarkdown,
  type OpenSpecHeadingSection,
  type OpenSpecProjectionOptions,
  type OpenSpecReadingSectionsProjection,
  type OpenSpecRequirementBlock,
  type OpenSpecScenarioBlock,
  type ProjectedOpenSpecDocument,
} from './openspec-projection.js'

// Document validation
export { Validator, type ValidationIssue, type ValidationResult } from './validator.js'

// Zod schemas and TypeScript types
export {
  FILE_PREVIEW_KINDS,
  inferFileMime,
  inferFilePreviewKind,
  isPreviewableFile,
  isTextLikeFile,
  isTextLikeMime,
  type FilePreviewKind,
} from './file-preview.js'

export {
  ChangeFileSchema,
  ChangeSchema,
  DeltaOperationType,
  DeltaSchema,
  DeltaSpecSchema,
  RequirementSchema,
  ScenarioStepKeywordSchema,
  ScenarioStepSchema,
  SpecSchema,
  TaskSchema,
  TrackedTaskProgressSchema,
  type Change,
  type ChangeFile,
  type Delta,
  type DeltaOperation,
  type DeltaSpec,
  type Requirement,
  type ScenarioStep,
  type Spec,
  type Task,
} from './schemas.js'

export {
  createApplyInstructionProgress,
  createDocumentChecklistSummary,
  createTrackedTaskProgress,
  deriveTrackedTaskPhase,
  isMarkdownTaskSourcePath,
  parseMarkdownTasks,
  projectTaskProjectionsFromMarkdownFiles,
  toggleMarkdownTask,
  type ApplyInstructionDivergence,
  type ApplyInstructionProgress,
  type ApplyInstructionState,
  type DocumentChecklistGroup,
  type DocumentChecklistSummary,
  type TaskProjectionOptions,
  type TaskProjections,
  type TrackedTask,
  type TrackedTaskLocation,
  type TrackedTaskPhase,
  type TrackedTaskProgress,
  type TrackedTaskSource,
} from './task-progress.js'

export {
  OwnedSpecIdentitySchema,
  ReferencedSpecIdentitySchema,
  SpecCatalogSchema,
  SpecCommandEvidenceSchema,
  SpecDocumentProjectionSchema,
  SpecIdentitySchema,
  buildSpecCatalog,
  createStaticSpecCatalogOwnedProjection,
  createStaticSpecCatalogReferenceProjection,
  createStaticSpecCatalogReferenceSource,
  getSpecCatalogEntry,
  isReferencedSpecIdentity,
  mergeSpecCatalog,
  specDocumentDisplayPath,
  specIdentityFromRoute,
  specIdentityKey,
  specRoutePath,
  type CliShowSpecDocument,
  type LiveReferencedSpecDocumentProjection,
  type LiveSpecCatalogOwnedProjection,
  type LiveSpecCatalogReferenceSource,
  type OwnedSpecCatalogEntry,
  type OwnedSpecDocumentProjection,
  type OwnedSpecIdentity,
  type ReferencedSpecCatalogEntry,
  type ReferencedSpecDocumentProjection,
  type ReferencedSpecIdentity,
  type SpecCatalog,
  type SpecCatalogEntry,
  type SpecCatalogOwnedProjection,
  type SpecCatalogReferenceProjection,
  type SpecCatalogReferenceSource,
  type SpecCommandEvidence,
  type SpecDocumentProjection,
  type SpecIdentity,
  type StaticReferencedSpecDocumentProjection,
  type StaticSpecCatalogOwnedProjection,
  type StaticSpecCatalogReferenceProjection,
  type StaticSpecCatalogReferenceSource,
} from './spec-catalog.js'

export {
  isBatchTranslationAbort,
  normalizeBatchTranslationError,
  runControlledTranslationTask,
  type BatchTranslationError,
  type BatchTranslationErrorKind,
} from './translation-task-control.js'

// Reactive file system for realtime updates
export {
  ActiveRootMutationSchema,
  ActiveRootOfficialConfigSchema,
  ActiveRootRevisionSchema,
  ActiveRootStructuredUpdateSchema,
  MAX_ACTIVE_ROOT_CONTEXT_BYTES,
  inspectActiveRootOfficialConfig,
  patchActiveRootOfficialFields,
  validateActiveRootRawYaml,
  type ActiveRootConfig,
  type ActiveRootConfigDiagnostic,
  type ActiveRootConfigFile,
  type ActiveRootConfigInspection,
  type ActiveRootMutation,
  type ActiveRootMutationResult,
  type ActiveRootOfficialConfig,
  type ActiveRootRawValidation,
  type ActiveRootRevision,
  type ActiveRootStructuredUpdate,
} from './active-root-config.js'
export {
  EnvironmentDefaultStoreUpdateSchema,
  EnvironmentGlobalConfigValueSchema,
  PlanningConfigJsonValueSchema,
  PlanningConfigReferenceSchema,
  ProjectBindingUpdateSchema,
  inspectEnvironmentDefaultStore,
  inspectProjectBinding,
  updateProjectBindingContent,
  type EnvironmentDefaultStoreState,
  type EnvironmentDefaultStoreUpdate,
  type EnvironmentGlobalCliProjection,
  type EnvironmentGlobalConfig,
  type EnvironmentGlobalFileProjection,
  type EnvironmentGlobalProfileState,
  type PlanningConfigDiagnostic,
  type PlanningConfigFile,
  type PlanningConfigReference,
  type ProjectBindingConfig,
  type ProjectBindingInspection,
  type ProjectBindingLaunchWrite,
  type ProjectBindingReferences,
  type ProjectBindingStore,
  type ProjectBindingTransition,
  type ProjectBindingUpdate,
  type ProjectBindingUpdateResult,
} from './planning-config.js'
export {
  // Low-level project watcher
  ProjectWatcher,
  ReactiveContext,
  ReactiveObservationEnvironment,
  // Core classes
  ReactiveState,
  acquireWatcher,
  acquireWatcherRoot,
  clearCache,
  closeAllProjectWatchers,
  closeAllWatchers,
  contextStorage,
  getActiveWatcherCount,
  getCacheSize,
  getProjectWatcher,
  getWatcherRuntimeStatus,
  isWatcherPoolInitialized,
  reactiveExists,
  reactiveReadDir,
  // Reactive file operations
  reactiveReadFile,
  reactiveStat,
  subscribeWatcherRuntimeStatus,
  updateReactiveFileCache,
  type ObservationEnvironmentRoot,
  type ObservationRootOwner,
  type PathCallback,
  type ProjectResidencyEvictionReason,
  type ProjectResidencyStatus,
  type ProjectWatcherReinitializeReason,
  type ProjectWatcherRuntimeStatus,
  type ProjectWatcherRuntimeStatusListener,
  type ReactiveContextStreamObserver,
  type ReactiveStateOptions,
  type WatchEvent,
  type WatchEventType,
  type WatcherRootRelease,
  type WatcherRootRuntimeStatus,
  type WatcherRuntimeStatus,
} from './reactive-fs/index.js'

// Legacy file watcher (deprecated, use reactive-fs instead)
export {
  OpenSpecWatcher,
  createFileChangeObservable,
  type FileChangeEvent,
  type FileChangeType,
} from './watcher.js'

// Configuration management
export {
  CODE_EDITOR_THEME_VALUES,
  CodeEditorThemeSchema,
  ConfigManager,
  DEFAULT_CONFIG,
  DEFAULT_GIT_DIFF_EAGER_LINE_BUDGET,
  DashboardConfigSchema,
  GitConfigSchema,
  OPSX_AGENT_INVOCATION_MODE_VALUES,
  OpenSpecUIConfigSchema,
  OpsxAgentInvocationModeSchema,
  OpsxConfigSchema,
  TerminalConfigSchema,
  TerminalRendererEngineSchema,
  TerminalThemeModeSchema,
  TerminalThemeSchema,
  buildCliRunnerCandidates,
  createCleanCliEnv,
  getDefaultCliCommand,
  getDefaultCliCommandString,
  isTerminalRendererEngine,
  parseCliCommand,
  sniffGlobalCli,
  type CliRunnerAttempt,
  type CliSniffResult,
  type CodeEditorTheme,
  type DashboardConfig,
  type GitConfig,
  type OpenSpecUIConfig,
  type OpenSpecUIConfigPresence,
  type OpenSpecUIConfigUpdate,
  type OpsxAgentInvocationMode,
  type OpsxConfig,
  type ResolvedCliRunner,
  type TerminalConfig,
  type TerminalRendererEngine,
  type TerminalThemeId,
  type TerminalThemeMode,
} from './config.js'

export {
  DEFAULT_GLOBAL_SETTINGS,
  DocumentTranslationGlobalSettingsUpdateSchema,
  GlobalSettingsManager,
  OpenSpecUIGlobalSettingsSchema,
  OpenSpecUIGlobalSettingsUpdateSchema,
  SERVE_PRESENTATION_MODES,
  ServePresentationModeSchema,
  getDefaultGlobalSettingsPath,
  toPersistedGlobalSettings,
  type OpenSpecUIGlobalSettings,
  type OpenSpecUIGlobalSettingsUpdate,
  type PersistedOpenSpecUIGlobalSettings,
  type ServePresentationMode,
} from './global-settings.js'

// Cross-platform non-shell child-process ownership
export {
  terminateChildProcessTree,
  terminateWindowsProcessTreeByIdentity,
} from './child-process-tree.js'
export {
  resolveCommandInvocation,
  resolveWindowsCommandInvocation,
  type CommandInvocation,
  type CommandInvocationOptions,
} from './command-invocation.js'
export { spawnSafe, type SafeSpawnResult } from './spawn-safe.js'

export {
  buildRuntimePackageInstallCommand,
  detectRuntimePackageManager,
  resolveRuntimePackageInstallStrategy,
  type RuntimePackageDependencyField,
  type RuntimePackageInstallCommand,
  type RuntimePackageInstallStrategy,
  type RuntimePackageManagerResolution,
  type RuntimePackageManagerSource,
} from './runtime-package-manager.js'

export {
  BUILTIN_SOUND_IDS,
  BUILTIN_SOUND_OPTIONS,
  BuiltinSoundIdSchema,
  CUSTOM_SOUND_ADD_VALUE,
  CustomSoundHashSchema,
  CustomSoundIdSchema,
  CustomSoundMetadataFileSchema,
  CustomSoundMetadataSchema,
  DEFAULT_BELL_SOUND_ID,
  DEFAULT_NOTIFICATION_SOUND_ID,
  LEGACY_SOUND_ID_MAP,
  SILENT_SOUND_ID,
  SoundConfigIdSchema,
  SoundIdSchema,
  customHashFromSoundId,
  getBuiltinSoundUrl,
  normalizeLegacySoundId,
  soundIdFromCustomHash,
  type BuiltinSoundId,
  type BuiltinSoundOption,
  type CustomSoundHash,
  type CustomSoundId,
  type CustomSoundMetadata,
  type CustomSoundMetadataFile,
  type SoundId,
} from './sounds.js'

export {
  TERMINAL_BELL_SOUND_OPTIONS,
  TERMINAL_BELL_SOUND_VALUES,
  TerminalBellSoundSchema,
  type TerminalBellSound,
} from './terminal-audio.js'

export {
  LOCAL_MODEL_PROFILE_DEFINITIONS,
  buildLocalDownloadPlanFromRepositoryFiles,
  buildLocalDownloadPlanFromRuntimeProfileFiles,
  selectLocalDownloadGroup,
  type LocalModelProfileId,
  type LocalRepositoryFile,
  type LocalRuntimeProfileFiles,
} from './local-download-profiles.js'

export {
  checkLocalDirectionalModelLanguagePair,
  inferLocalDirectionalModelLanguagePair,
  type LocalDirectionalModelLanguagePairCheck,
  type TranslationLanguagePair,
} from './translation-language-pair.js'

export {
  BatchTranslateEventSchema,
  BatchTranslateInputSchema,
  DEFAULT_TRANSLATION_ENGINE_ID,
  LocalModelAssetLogSchema,
  LocalModelAssetPlanSnapshotSchema,
  LocalModelAssetStateSchema,
  LocalModelDownloadStatusSchema,
  LocalModelLifecycleFileStateSchema,
  LocalModelLifecycleGroupStateSchema,
  LocalModelProfileLoadStateSchema,
  LocalModelProfileManifestFileSchema,
  LocalModelProfileManifestGroupSchema,
  LocalModelProfileManifestSchema,
  LocalModelProfileStatusSchema,
  ManagedLocalCatalogSourceSchema,
  SERVICE_TRANSLATION_ENGINE_IDS,
  ServiceTranslationEngineIdSchema,
  TRANSLATION_ENGINE_IDS,
  TRANSLATION_ENGINE_MANIFESTS,
  TRANSLATOR_CONTRACT_VERSION,
  TranslationDownloadFilePlanSchema,
  TranslationDownloadGroupPlanSchema,
  TranslationEngineAssetStateSchema,
  TranslationEngineAssetStatusSchema,
  TranslationEngineDependencyStateSchema,
  TranslationEngineDependencyStatusSchema,
  TranslationEngineGlobalSettingsSchema,
  TranslationEngineGlobalSettingsUpdateSchema,
  TranslationEngineIdSchema,
  TranslationEngineInstallLogEventSchema,
  TranslationEngineInstallLogStreamSchema,
  TranslationEngineLifecycleEventSchema,
  TranslationEngineLifecycleStatusSchema,
  TranslationEngineRuntimeStateSchema,
  TranslationEngineRuntimeStatusSchema,
  TranslationLocalCt2SettingsSchema,
  TranslationLocalCt2SettingsUpdateSchema,
  TranslationLocalLlamaSettingsSchema,
  TranslationLocalLlamaSettingsUpdateSchema,
  TranslationLocalSettingsSchema,
  TranslationLocalSettingsUpdateSchema,
  TranslationOpenAISettingsSchema,
  TranslationOpenAISettingsUpdateSchema,
  createTranslationEngineLifecycleStatus,
  getManagedLocalTranslationEngineManifest,
  getTranslationEngineLifecycleMessage,
  getTranslationEngineManifest,
  isDirectionalManagedLocalTranslationEngineId,
  isManagedLocalTranslationEngineId,
  isTranslationEngineDependencyReady,
  isTranslationEngineRuntimeReady,
  shouldShowTranslationEngineInstallGate,
  type BatchTranslateEvent,
  type BatchTranslateInput,
  type BatchTranslationResult,
  type LocalModelAssetLog,
  type LocalModelAssetPlanSnapshot,
  type LocalModelAssetState,
  type LocalModelCatalogItem,
  type LocalModelCatalogLocalResult,
  type LocalModelCatalogResult,
  type LocalModelCatalogSearchEvent,
  type LocalModelDownloadStatus,
  type LocalModelLifecycleFileState,
  type LocalModelLifecycleGroupState,
  type LocalModelProfileLoadState,
  type LocalModelProfileManifest,
  type LocalModelProfileManifestFile,
  type LocalModelProfileManifestGroup,
  type LocalModelProfileStatus,
  type ManagedLocalCatalogSource,
  type ManagedLocalTranslationEngineId,
  type ServiceTranslationEngineId,
  type TranslationDownloadFilePlan,
  type TranslationDownloadGroupPlan,
  type TranslationEngineAssetState,
  type TranslationEngineAssetStatus,
  type TranslationEngineDependencyState,
  type TranslationEngineDependencyStatus,
  type TranslationEngineGlobalSettings,
  type TranslationEngineGlobalSettingsUpdate,
  type TranslationEngineId,
  type TranslationEngineInstallLogEvent,
  type TranslationEngineInstallLogStream,
  type TranslationEngineKind,
  type TranslationEngineLifecycleContext,
  type TranslationEngineLifecycleController,
  type TranslationEngineLifecycleEvent,
  type TranslationEngineLifecycleStatus,
  type TranslationEngineManifest,
  type TranslationEngineRuntime,
  type TranslationEngineRuntimeState,
  type TranslationEngineRuntimeStatus,
  type TranslationEngineSettingsKey,
  type TranslationLocalCt2Settings,
  type TranslationLocalLlamaSettings,
  type TranslationLocalSettings,
  type TranslationModelCandidate,
  type TranslationModelDownloadPlan,
  type TranslationModelSearchEvent,
  type TranslationModelSearchInput,
  type TranslationModelSearchPhase,
  type TranslationModelSearchResult,
  type TranslationOpenAISettings,
  type Translator,
  type TranslatorCreateMonitor,
  type TranslatorFactory,
  type TranslatorFactoryCreateOptions,
  type TranslatorFactoryPrepareOptions,
  type TranslatorOptions,
  type TranslatorPrepareMonitor,
} from './translator.js'

export {
  DEFAULT_TRANSLATION_CACHE_ENTRY_LIMIT,
  DOCUMENT_TRANSLATION_DISPLAY_MODES,
  DocumentTranslationConfigSchema,
  DocumentTranslationConfigUpdateSchema,
  DocumentTranslationDisplayModeSchema,
  MAX_TRANSLATION_CACHE_ENTRY_LIMIT,
  MIN_TRANSLATION_CACHE_ENTRY_LIMIT,
  TRANSLATION_CACHE_POLICY_VERSION,
  TranslationCacheEntrySchema,
  TranslationCacheReadInputSchema,
  TranslationCacheSettingsSchema,
  TranslationCacheSettingsUpdateSchema,
  TranslationCacheStatsSchema,
  TranslationCacheWriteInputSchema,
  TranslationEngineProjectSettingsSchema,
  TranslationEngineProjectSettingsUpdateSchema,
  type DocumentTranslationConfig,
  type DocumentTranslationConfigInput,
  type DocumentTranslationConfigUpdate,
  type DocumentTranslationDisplayMode,
  type TranslationCacheEntry,
  type TranslationCacheReadInput,
  type TranslationCacheSettings,
  type TranslationCacheStats,
  type TranslationCacheWriteInput,
  type TranslationEngineProjectSettings,
} from './document-translation.js'

export {
  NOTIFICATION_SOUND_OPTIONS,
  NOTIFICATION_SOUND_VALUES,
  NotificationActionSchema,
  NotificationGroupKeySchema,
  NotificationPublishInputSchema,
  NotificationRecordSchema,
  NotificationSettingsSchema,
  NotificationSoundSchema,
  NotificationSourceSchema,
  TerminalNotificationParser,
  getNotificationGroupKey,
  getNotificationGroupLabel,
  groupNotifications,
  terminalNotificationEventToPublishInput,
  type NotificationAction,
  type NotificationGroup,
  type NotificationGroupKey,
  type NotificationPublishInput,
  type NotificationRecord,
  type NotificationSettings,
  type NotificationSound,
  type NotificationSource,
  type TerminalNotificationEvent,
  type TerminalNotificationParseResult,
} from './notifications.js'

export {
  TerminalControlParser,
  type TerminalControlEvent,
  type TerminalControlParseResult,
  type TerminalNotificationProtocol,
  type TerminalProgressState,
  type TerminalPromptState,
  type TerminalTitleTarget,
} from './terminal-control.js'

// CLI executor for calling external openspec commands
export {
  CliExecutor,
  CliStreamTerminationError,
  type CliResult,
  type CliStreamEvent,
  type CliStreamHandle,
  type CliStreamSettlement,
} from './cli-executor.js'

export {
  OPENSPEC_SPAWN_MODE_ENV,
  resolveOpenSpecSpawnMode,
  type OpenSpecSpawnMode,
} from './openspec-cli-worker.js'

export {
  compareAndWriteAtomicPhysicalReactiveFile,
  createPhysicalReactiveDirectory,
  removePhysicalReactivePath,
  replaceFileAtomically,
  runPhysicalReactivePathMutation,
  writeAtomicPhysicalReactiveFile,
  writePhysicalReactiveFile,
  type PhysicalReactiveFileCompareWrite,
  type PhysicalReactiveFileCompareWriteResult,
  type PhysicalReactiveFileWrite,
  type PhysicalReactivePathTarget,
} from './physical-reactive-file-writer.js'

export {
  CliApplyInstructionsSchema,
  CliArchiveInstructionsSchema,
  CliArchiveSchema,
  CliArtifactInstructionsSchema,
  CliChangeListSchema,
  CliContextSchema,
  CliDiagnosticFailureSchema,
  CliDiagnosticSchema,
  CliDoctorReferenceEntrySchema,
  CliDoctorSchema,
  CliReferenceIndexEntrySchema,
  CliRootSchema,
  CliRootSourceSchema,
  CliShowSpecDocumentSchema,
  CliShowSpecSchema,
  CliSpecListSchema,
  CliStoreCleanupSchema,
  CliStoreDoctorEntrySchema,
  CliStoreDoctorSchema,
  CliStoreListSchema,
  CliStoreMutationSchema,
  CliStoreSchema,
  CliValidateReportSchema,
  CliValidateSchema,
  CliWorkflowStatusSchema,
  OpenSpecCliContractExecutor,
  parseCliCommandResult,
  type CliApplyInstructions,
  type CliArchive,
  type CliArchiveInstructions,
  type CliArtifactInstructions,
  type CliChangeList,
  type CliCommandResult,
  type CliContext,
  type CliDiagnostic,
  type CliDiagnosticFailure,
  type CliDoctor,
  type CliDoctorReferenceEntry,
  type CliJsonValue,
  type CliReferenceIndexEntry,
  type CliRoot,
  type CliRootSelector,
  type CliRootSource,
  type CliShowSpec,
  type CliSpecList,
  type CliStore,
  type CliStoreCleanup,
  type CliStoreDoctor,
  type CliStoreDoctorEntry,
  type CliStoreList,
  type CliStoreMutation,
  type CliStoreRegisterOptions,
  type CliStoreRemoveOptions,
  type CliStoreSetupOptions,
  type CliValidate,
  type CliValidateJsonOptions,
  type CliValidateTarget,
  type CliWorkflowOptions,
  type CliWorkflowStatus,
} from './cli-contracts/index.js'

export {
  CliJsonValueSchema,
  CliProjectionCommandError,
  CliProjectionCommandEvidenceSchema,
  CliProjectionFailureSchema,
  CliProjectionInvalidationCauseSchema,
  CliProjectionNoticeSchema,
  CliProjectionStateNameSchema,
  cliProjectionStates,
  createCliProjectionStateSchema,
  toCliProjectionCommandEvidence,
  toCliProjectionFailure,
  toCliProjectionNotice,
  type CliProjectionCommandEvidence,
  type CliProjectionFailure,
  type CliProjectionInvalidationCause,
  type CliProjectionNotice,
  type CliProjectionState,
  type CliProjectionStateName,
} from './cli-projection.js'
export {
  OPEN_SPEC_DATA_HOME_OBSERVATION_TARGETS,
  OpenSpecDataHomeObserver,
  type OpenSpecDataHomeObservationState,
  type OpenSpecDataHomeObserverOptions,
} from './open-spec-data-home-observer.js'
export {
  OPEN_SPEC_DATA_DIRECTORY_NAME,
  resolveOpenSpecDataScope,
  type OpenSpecDataScope,
  type OpenSpecDataScopeSource,
  type ResolveOpenSpecDataScopeOptions,
} from './open-spec-data-scope.js'
export {
  EnvironmentGlobalFileProjectionDataSchema,
  EnvironmentGlobalFileProjectionStateSchema,
  EnvironmentGlobalProjectionDataSchema,
  EnvironmentGlobalProjectionStateSchema,
  PlanningCliProjectionDataSchema,
  PlanningCliProjectionSelectorSchema,
  PlanningCliProjectionStateSchema,
  type EnvironmentGlobalFileProjectionData,
  type EnvironmentGlobalFileProjectionState,
  type EnvironmentGlobalProjectionData,
  type EnvironmentGlobalProjectionState,
  type PlanningCliProjectionData,
  type PlanningCliProjectionSelector,
  type PlanningCliProjectionState,
} from './planning-cli-projection.js'
export {
  getRootContextCliSelector,
  resolveRootContext,
  type ResolveRootContextOptions,
  type RootContext,
  type RootContextCli,
  type RootContextCliAvailability,
  type RootContextCliExecutor,
  type RootContextCommandEvidence,
  type RootContextError,
  type RootContextErrorCode,
  type RootContextResolvedState,
  type RootContextState,
} from './root-context.js'
export {
  RUNTIME_INVALIDATION_FACETS,
  RuntimeInvalidationIndex,
  type RuntimeInvalidationController,
  type RuntimeInvalidationFacet,
  type RuntimeInvalidationListener,
  type RuntimeInvalidationReader,
  type RuntimeInvalidationToken,
} from './runtime-invalidation.js'
export {
  RuntimeRootInvalidationRegistry,
  type RuntimeInvalidationRoot,
  type RuntimeRootInvalidationOwner,
} from './runtime-root-invalidation.js'

// Tool configuration detection
export {
  AI_TOOLS,
  getAllToolIds,
  getAllTools,
  getAvailableToolIds,
  getAvailableTools,
  getConfiguredTools,
  getDetectedProjectTools,
  getToolById,
  isToolConfigured,
  type AIToolOption,
  type AgentCommandArtifact,
  type AgentCommandContentFormat,
  type AgentCommandFormat,
  type AgentCommandInvocationStyle,
  type AgentCommandSurfaceCapability,
  type AgentDeliveryCleanup,
  type AgentDeliveryMigration,
  type ToolConfig,
} from './tool-config.js'

export {
  AgentDeliveryModeSchema,
  AgentDeliveryPolicyUpdateSchema,
  AgentDeliveryProfileSchema,
  AgentDeliveryWorkflowSchema,
  applyAgentDeliveryPolicy,
  normalizeAgentDeliveryPolicy,
  type AgentDeliveryMode,
  type AgentDeliveryPolicy,
  type AgentDeliveryPolicyUpdate,
  type AgentDeliveryProfile,
} from './agent-delivery-policy.js'

export {
  loadOpenSpecAgentCommandContents,
  type AgentCommandContentCatalog,
  type AgentCommandContentResult,
} from './agent-command-content.js'
export { selectAgentDeliveryRegistry } from './agent-delivery-registry.js'

// Tool initialization state detection
export {
  PINNED_AGENT_GENERATOR_VERSION,
  TOOL_WORKFLOW_TO_SKILL_DIR,
  createToolInitStateProjection,
  getExternalAgentSkillsObservationRoots,
  getExternalCodexCommandObservationRoot,
  getToolInitStates,
  resolveGlobalSkillsInventoryDir,
  resolveToolSkillsScope,
  type ToolInitCleanupState,
  type ToolInitDelivery,
  type ToolInitIssue,
  type ToolInitMigrationState,
  type ToolInitProjectionOptions,
  type ToolInitReadiness,
  type ToolInitState,
  type ToolInitStatus,
  type ToolSkillsScope,
  type ToolWorkflowId,
} from './tool-init-state.js'

// Export types for static site generation
export {
  DashboardSummaryIdentitySchema,
  DashboardSummaryInvalidationCauseSchema,
  DashboardSummaryInvalidationSchema,
  DashboardSummaryProjectionStateSchema,
  type DashboardSummaryIdentity,
  type DashboardSummaryInvalidation,
  type DashboardSummaryInvalidationCause,
  type DashboardSummaryProjectionState,
} from './dashboard-summary-transport.js'
export {
  DASHBOARD_METRIC_KEYS,
  DashboardGitSnapshotSchema,
  DashboardOverviewSchema,
  DashboardSummaryProjectionSchema,
  DashboardTrendsProjectionSchema,
  type DashboardCardAvailability,
  type DashboardGitCommitEntry,
  type DashboardGitDiffStats,
  type DashboardGitEntry,
  type DashboardGitSnapshot,
  type DashboardGitUncommittedEntry,
  type DashboardGitWorktree,
  type DashboardMetricKey,
  type DashboardOverview,
  type DashboardSummary,
  type DashboardSummaryProjection,
  type DashboardTrendKind,
  type DashboardTrendMeta,
  type DashboardTrendPoint,
  type DashboardTrendsProjection,
  type DashboardTriColorTrendPoint,
} from './dashboard-types.js'
export {
  type ExportReferencePolicy,
  type ExportRootProvenance,
  type ExportRootSource,
  type ExportSnapshot,
  type StaticSchemasCaptureFailure,
} from './export-types.js'
export {
  type GitEntriesPage,
  type GitEntryCursor,
  type GitEntryDetail,
  type GitEntryFileDiff,
  type GitEntryFilePatch,
  type GitEntryFileSource,
  type GitEntryFileSummary,
  type GitEntryFiles,
  type GitEntryPatch,
  type GitEntrySelector,
  type GitEntryShell,
  type GitFileChangeType,
  type GitPatchFile,
  type GitPatchState,
  type GitRepositoryIdentity,
  type GitRepositoryScope,
  type GitRepositoryScopeDescriptor,
  type GitRepositoryScopes,
  type GitWorktreeHandoff,
  type GitWorktreeOverview,
  type GitWorktreeSummary,
  type StaticGitRepositoryScopeDescriptor,
  type StaticGitRepositoryScopes,
} from './git-panel-types.js'
export {
  OPENSPECUI_DOCUMENT_HOOK_VERSION,
  OPENSPECUI_WORKFLOW_HOOK_VERSION,
  type DocumentConsumerV1,
  type DocumentReadModeV1,
  type DocumentRefV1,
  type HookDiagnosticLevel,
  type HookDiagnosticV1,
  type HookLifecycleV1,
  type OnReadDocumentHookV1,
  type OnRunWorkflowHookV2,
  type OpenSpecUIHooks,
  type ReadDocumentContextV1,
  type ReadDocumentResultV1,
  type RunWorkflowContextV2,
  type RunWorkflowInputV1,
  type RunWorkflowResultV2,
  type WorkflowActionEvidenceV2,
  type WorkflowActionV1,
  type WorkflowInvocationModeResolutionV1,
  type WorkflowInvocationTargetV2,
  type WorkflowRequestedModeV1,
} from './hooks.js'
export {
  HOSTED_SHELL_PROTOCOL_VERSION,
  OFFICIAL_APP_BASE_URL,
  OPENSPECUI_RUNTIME_CAPABILITIES,
  buildBackendHealthPayload,
  buildEmbeddedUiLaunchUrl,
  buildHostedLaunchUrl,
  isBackendHealthRuntimeMetadata,
  isHostedBackendHealthResponse,
  isSupportedEmbeddedUiUrl,
  normalizeEmbeddedUiUrl,
  normalizeHostedAppBaseUrl,
  resolveHostedAppBaseUrl,
  type HostedBackendHealthResponse,
  type OpenSpecUIRuntimeCapability,
} from './hosted-app.js'
export {
  ACCESS_GATE_CREDENTIAL_BYTES,
  accessGateFingerprint,
  asEnvUri,
  computeEnvUri,
  constantTimeEqual,
  generateAccessGateCredential,
  hasCapability,
  isTerminalMutationStatus,
  normalizeAccessGatePassword,
  type AccessGateCredential,
  type EnvUri,
  type StoreCapability,
  type StoreCapabilitySet,
  type StoreMutation,
  type StoreMutationKind,
  type StoreMutationResult,
  type StoreMutationStatus,
} from './hosted-protocol.js'
export { VIRTUAL_PROJECT_DIRNAME, toOpsxDisplayPath } from './opsx-display-path.js'
export {
  OPSX_ALL_WORKFLOWS,
  OPSX_ARTIFACT_INPUT_ACTIONS,
  OPSX_CHANGE_INPUT_ACTIONS,
  OPSX_COMMAND_CAPABLE_WORKFLOWS,
  OPSX_CORE_PROFILE_WORKFLOWS,
  OPSX_TEXT_INPUT_ACTIONS,
  OPSX_WORKFLOW_LABELS,
  OPSX_WORKFLOW_TO_SKILL_DIR,
  isOpsxCoreWorkflowSelection,
  type OpsxArtifactInputAction,
  type OpsxChangeInputAction,
  type OpsxTextInputAction,
  type OpsxWorkflowId,
} from './opsx-workflows.js'
export { type ProjectRecoveryStatus } from './runtime-types.js'
export { redactSnapshotForPublication, snapshotHasAbsolutePath } from './snapshot-redaction.js'
export {
  StoreMutationLifecycleEventSchema,
  StoreMutationResultSchema,
  StoreMutationSchema,
  StoreMutationStartResponseSchema,
  type StoreMutationEnvelope,
  type StoreMutationLifecycleEvent,
  type StoreMutationResultEnvelope,
  type StoreMutationStartResponse,
} from './store-mutation-protocol.js'
export {
  StoreDoctorResultSchema,
  StoreListResultSchema,
  classifyStoreCliResult,
  toStoreFeatureResult,
  type StoreClassification,
  type StoreCommandEvidence,
  type StoreCommandUnavailableError,
  type StoreDataIncompatibleError,
  type StoreDiagnostic,
  type StoreDoctorResult,
  type StoreDoctorStore,
  type StoreFeatureError,
  type StoreFeatureResult,
  type StoreListEntry,
  type StoreListResult,
} from './store-types.js'
export {
  BUILTIN_TERMINAL_SPAWN_COMMANDS,
  TERMINAL_COMMAND_FIELD_TYPE_VALUES,
  TERMINAL_SHELL_QUOTE_STYLE_VALUES,
  TerminalCommandFieldSchema,
  TerminalInvocationSettingsSchema,
  TerminalShellProfileSchema,
  TerminalShellQuoteStyleSchema,
  TerminalSpawnCommandSchema,
  getTerminalCommandDefaultValues,
  quoteTerminalShellArg,
  renderTerminalCommandArgs,
  renderTerminalSpawnCommandLine,
  resolveTerminalShellDefaults,
  type TerminalCommandArgument,
  type TerminalCommandField,
  type TerminalCommandFieldValue,
  type TerminalCommandFieldValues,
  type TerminalInvocationSettings,
  type TerminalShellDefaults,
  type TerminalShellProfile,
  type TerminalShellQuoteStyle,
  type TerminalSpawnCommand,
} from './terminal-invocation.js'
export {
  DEFAULT_TERMINAL_DARK_THEME,
  DEFAULT_TERMINAL_LIGHT_THEME,
  DEFAULT_TERMINAL_THEME_MODE,
  TERMINAL_THEME_MODE_VALUES,
  TERMINAL_THEME_VALUES,
} from './terminal-theme.js'

// OPSX Kernel - reactive in-memory data store
export { OpsxKernel } from './opsx-kernel.js'

// OPSX CLI output schemas and types
export {
  requireCanonicalOpenSpecEntityId,
  requireCanonicalOpenSpecSpecId,
  requireOpenSpecEntityRelativePath,
  type OpenSpecEntityIdField,
  type OpenSpecEntityPathField,
} from './entity-id.js'
export {
  buildOpsxEntityDetail,
  getOpsxEntityMetadataPath,
  getOpsxEntityRootRelativePath,
  isOpsxGlobPattern,
  normalizeOpsxEntityPath,
  opsxGlobToRegex,
  opsxPathMatchesPattern,
  parseOpsxEntityMetadata,
  type OpsxEntityArtifact,
  type OpsxEntityArtifactFile,
  type OpsxEntityDetail,
  type OpsxEntityDiagnostic,
  type OpsxEntityFile,
  type OpsxEntityReadOptions,
  type OpsxEntityStage,
} from './opsx-entity.js'
export { parseOpsxSchemaDetail, type ParsedOpsxSchemaDetail } from './opsx-schema-detail.js'
export {
  ApplyInstructionsContextFilesSchema,
  ApplyInstructionsProjectionSchema,
  ApplyInstructionsSchema,
  ApplyTaskSchema,
  ArchiveInstructionsSchema,
  ArtifactInstructionsSchema,
  ArtifactStatusSchema,
  ChangeStatusSchema,
  DependencyInfoSchema,
  OpsxCliEvidenceSchema,
  OpsxConfigBundleSchema,
  OpsxStatusEvidenceSchema,
  SchemaArtifactSchema,
  SchemaDetailSchema,
  SchemaInfoSchema,
  SchemaResolutionSchema,
  TemplateContentMapSchema,
  TemplateContentSchema,
  TemplatesSchema,
  isGlobPattern,
  type ApplyInstructions,
  type ApplyTask,
  type ArchiveInstructions,
  type ArtifactInstructions,
  type ArtifactStatus,
  type ChangeStatus,
  type DependencyInfo,
  type OpsxCliEvidence,
  type OpsxConfigBundle,
  type OpsxStatusEvidence,
  type SchemaArtifact,
  type SchemaDetail,
  type SchemaInfo,
  type SchemaResolution,
  type TemplateContentMap,
  type TemplatesMap,
} from './opsx-types.js'

// PTY WebSocket protocol schemas and types
export {
  PtyAttachMessageSchema,
  PtyBellResponseSchema,
  PtyBufferResponseSchema,
  PtyClientMessageSchema,
  PtyCloseMessageSchema,
  PtyCreateMessageSchema,
  PtyCreatedResponseSchema,
  PtyErrorCodeSchema,
  PtyErrorResponseSchema,
  PtyExitResponseSchema,
  PtyInputMessageSchema,
  PtyListMessageSchema,
  PtyListResponseSchema,
  PtyOutputResponseSchema,
  PtyPlatformSchema,
  PtyProcessTitleResponseSchema,
  PtyResizeMessageSchema,
  PtyServerMessageSchema,
  PtyTitleResponseSchema,
  TerminalCwdTargetSchema,
  type PtyClientMessage,
  type PtyPlatform,
  type PtyServerMessage,
  type PtySessionInfo,
  type TerminalCwdTarget,
} from './pty-protocol.js'
