/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Ct2Translator {
  constructor(options: Ct2TranslatorOptions)
  translateBatch(
    source: Array<string>,
    options?: TranslateBatchOptions | undefined | null
  ): Promise<Array<TranslationResult>>
}

export interface Ct2TranslatorOptions {
  modelPath: string
  device?: string
  threads?: number
}

export interface TranslateBatchOptions {
  beamSize?: number
  maxBatchSize?: number
  returnScores?: boolean
}

export interface TranslationResult {
  text: string
  score?: number
}
