/**
 * Orthogonal intents (updated 2026-08-02 Asia/Shanghai):
 * 1. Configure the hosted App, CLI runtime projection, and development endpoint.
 * 2. Resolve browser-safe Workspace, daemon catalog, and Store mutation protocol source entries.
 * 3. Project hand-designed native App identity variants into the App public tree.
 *
 * Original request (2026-07-24): "apply openspec-change: close-openspec-cli16-delivery-gaps"
 * Owner direction (2026-07-29): the bundled App consumes the shared daemon control contract.
 * Owner correction (2026-07-30): every App build projects its assets into the CLI package.
 * Owner correction (2026-07-31): PWA manifest and service-worker build outputs are retired.
 * Owner correction (2026-08-02): native App identity variants are generated by
 *   scripts/build-native-icons.ts (hand-designed light/dark PNGs); this Vite plugin only
 *   copies the committed resources/app-icon catalog into the App public tree.
 */
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'
import { createHash } from 'node:crypto'
import { existsSync, readdirSync, readFileSync } from 'node:fs'
import { cp, rm } from 'node:fs/promises'
import { relative, resolve } from 'node:path'
import { defineConfig, type Plugin } from 'vite'
import { hostedAppPlugin } from './src/vite-plugin-hosted-app'

function collectHostedShellRevisionSeed(rootDir: string): string {
  const files = [
    resolve(rootDir, 'package.json'),
    ...collectFiles(resolve(rootDir, 'src')),
    ...collectFiles(resolve(rootDir, 'public')),
  ]
  const hash = createHash('sha256')
  for (const file of files) {
    hash.update(relative(rootDir, file))
    hash.update(readFileSync(file))
  }
  return hash.digest('hex').slice(0, 12)
}

function collectFiles(dir: string): string[] {
  const entries = readdirSync(dir, { withFileTypes: true })
  return entries.flatMap((entry) => {
    const fullPath = resolve(dir, entry.name)
    if (entry.isDirectory()) {
      return collectFiles(fullPath)
    }
    return [fullPath]
  })
}

const NATIVE_ICONS_SOURCE = resolve(__dirname, '..', '..', 'resources', 'app-icon')
const NATIVE_ICONS_TARGET = resolve(__dirname, 'public', 'native-icons', 'app-icon')

/**
 * Copy the committed resources/app-icon variant catalog into the App public tree.
 * Native variants (darwin/win32 light+dark, linux PNGs) are generated upstream by
 * scripts/build-native-icons.ts; the App build must only project them verbatim.
 */
function copyNativeIconVariantsPlugin(): Plugin {
  return {
    name: 'openspecui-copy-native-icon-variants',
    apply: 'build',
    async buildStart() {
      if (!existsSync(NATIVE_ICONS_SOURCE)) {
        throw new Error(
          `native app-icon catalog missing at ${NATIVE_ICONS_SOURCE}. Run "pnpm build:native-icons" first.`
        )
      }
      await rm(NATIVE_ICONS_TARGET, { force: true, recursive: true })
      await cp(NATIVE_ICONS_SOURCE, NATIVE_ICONS_TARGET, { force: true, recursive: true })
    },
  }
}

export default defineConfig({
  base: '/',
  define: {
    __OPENSPECUI_APP_SHELL_REVISION__: JSON.stringify(collectHostedShellRevisionSeed(__dirname)),
  },
  plugins: [copyNativeIconVariantsPlugin(), react(), tailwindcss(), hostedAppPlugin()],
  resolve: {
    alias: {
      '@': resolve(__dirname, './src'),
      '@openspecui/core': resolve(__dirname, '../core/src'),
      '@openspecui/core/hosted-app': resolve(__dirname, '../core/src/hosted-app.ts'),
      '@openspecui/core/app-daemon-control': resolve(
        __dirname,
        '../core/src/app-daemon-control.ts'
      ),
      '@openspecui/core/workspace-directory-catalog': resolve(
        __dirname,
        '../core/src/workspace-directory-catalog.ts'
      ),
      '@openspecui/core/store-types': resolve(__dirname, '../core/src/store-types.ts'),
      '@openspecui/core/store-mutation-protocol': resolve(
        __dirname,
        '../core/src/store-mutation-protocol.ts'
      ),
      '@openspecui/web-src': resolve(__dirname, '../web/src'),
    },
  },
  server: {
    host: '127.0.0.1',
    port: 13005,
    strictPort: false,
  },
  build: {
    outDir: 'dist',
    rollupOptions: {
      input: {
        app: resolve(__dirname, 'index.html'),
      },
      output: {
        entryFileNames: 'assets/[name]-[hash].js',
        chunkFileNames: 'assets/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash][extname]',
      },
    },
  },
})
