export {
  OPENSPECUI_DOCUMENT_HOOK_VERSION,
  OPENSPECUI_WORKFLOW_HOOK_VERSION,
} from '@openspecui/core'
export type {
  DocumentConsumerV1,
  DocumentReadModeV1,
  DocumentRefV1,
  HookDiagnosticLevel,
  HookDiagnosticV1,
  HookLifecycleV1,
  OnReadDocumentHookV1,
  OnRunWorkflowHookV2,
  OpenSpecUIHooks,
  ReadDocumentContextV1,
  ReadDocumentResultV1,
  RunWorkflowContextV2,
  RunWorkflowInputV1,
  RunWorkflowResultV2,
  WorkflowActionEvidenceV2,
  WorkflowActionV1,
  WorkflowInvocationModeResolutionV1,
  WorkflowInvocationTargetV2,
  WorkflowRequestedModeV1,
} from '@openspecui/core'
