/**
 * Orthogonal intents (created 2026-07-30 Asia/Shanghai):
 * 1. Project Vite-generated native assets into platform-correct OpenTray App identity catalogs.
 * 2. Project one compact transparent logo into platform-specific tray icon candidates.
 *
 * Owner request (2026-07-30): "logo要全面应用：titlebar中、appIcon中、trayIcon中。"
 * Owner correction (2026-07-30): App assets are generated by `openTrayAppIconPlugin`.
 */
import { join } from 'node:path'
import type { AppIcon, Icon } from 'opentray'

export interface OpenTrayBrandAssets {
  appIcon: AppIcon | null
  trayIcon: Icon
}

/** Resolve brand assets from the same App tree served and packaged by the CLI. */
export function resolveOpenTrayBrandAssets(
  appAssetsDir: string,
  platform: NodeJS.Platform
): OpenTrayBrandAssets {
  const trayIconPath = join(appAssetsDir, 'native-icons', 'tray-icon.png')
  const trayIcon: Icon = {
    'darwin-icon-only': { type: 'file', path: trayIconPath, isTemplate: true },
    'win32-icon-only': { type: 'file', path: trayIconPath },
    'linux-icon-only': { type: 'file', path: trayIconPath },
  }

  if (platform === 'darwin') {
    return {
      trayIcon,
      appIcon: [
        {
          platform: 'darwin',
          format: 'icns',
          source: { type: 'file', path: join(appAssetsDir, 'native-icons', 'app-icon.icns') },
        },
      ],
    }
  }
  if (platform === 'win32') {
    return {
      trayIcon,
      appIcon: [
        {
          platform: 'windows',
          format: 'ico',
          source: { type: 'file', path: join(appAssetsDir, 'native-icons', 'app-icon.ico') },
        },
      ],
    }
  }
  if (platform === 'linux') {
    return {
      trayIcon,
      appIcon: [
        {
          platform: 'linux',
          format: 'png',
          size: 512,
          source: {
            type: 'file',
            path: join(appAssetsDir, 'native-icons', 'linux', '512x512', 'app-icon.png'),
          },
        },
      ],
    }
  }
  return { appIcon: null, trayIcon }
}
