/**
 * Orthogonal intents (created 2026-07-30 Asia/Shanghai):
 * 1. Prove each supported platform receives its generated standards-correct App identity format.
 * 2. Prove tray candidates share one bundled logo and macOS declares template behavior.
 *
 * Owner request (2026-07-30): "logo要全面应用：titlebar中、appIcon中、trayIcon中。"
 * Owner correction (2026-07-30): App assets are generated by `openTrayAppIconPlugin`.
 */
import { describe, expect, it } from 'vitest'
import { resolveOpenTrayBrandAssets } from './opentray-brand-assets.js'

describe('OpenTray brand assets', () => {
  it.each([
    ['darwin', 'darwin', 'icns', '/package/app/native-icons/app-icon.icns'],
    ['win32', 'windows', 'ico', '/package/app/native-icons/app-icon.ico'],
    ['linux', 'linux', 'png', '/package/app/native-icons/linux/512x512/app-icon.png'],
  ] as const)('projects the App logo for %s', (platform, catalogPlatform, format, path) => {
    const brand = resolveOpenTrayBrandAssets('/package/app', platform)

    expect(brand.appIcon).toEqual([
      expect.objectContaining({
        platform: catalogPlatform,
        format,
        source: { type: 'file', path },
      }),
    ])
    expect(brand.trayIcon).toEqual({
      'darwin-icon-only': {
        type: 'file',
        path: '/package/app/native-icons/tray-icon.png',
        isTemplate: true,
      },
      'win32-icon-only': {
        type: 'file',
        path: '/package/app/native-icons/tray-icon.png',
      },
      'linux-icon-only': {
        type: 'file',
        path: '/package/app/native-icons/tray-icon.png',
      },
    })
  })
})
